### ISSUE TITLE
Update metno pycsw container to using version 2.6.0 of pycsw

### ISSUE THREAD

**Issue by mortenwh** [metno/pycsw-container#4]
@mortenwh commented on [Mon Dec 07 2020](https://github.com/metno/S-ENDA-project-plan/issues/405)

It should be enough to update the `PYCSW_VERSION` environment variable.

**Comment by mortenwh** [comment]
Seems apk only has version 7.1 of proj. @aheimsbakk @epifanio - what do we do? Do we need an alpine based image in production, or even our own image? Or can we do with the one from geopython/pycsw?

Since this starts to be a critical tool, we also need to agree about maintenance responsibilities. Any opinions about how we should handle that?

```
    default:   ERROR: Command errored out with exit status 1:
    default:    command: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp32zl698p
    default:        cwd: /tmp/pip-install-wfyb1gz8/pyproj_91f489c0cdf7461c8668f5f48ea09770
    default:   Complete output (1 lines):
    default:   ERROR: Minimum supported proj version is 7.2.0, installed version is 6.2.1. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
    default:   ----------------------------------------
    default: 
    default: ERROR: Command errored out with exit status 1: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp32zl698p Check the logs for full command output.
    default: 
    default: Service 'sut' failed to build: The command '/bin/sh -c apk add --no-cache --virtual .build-deps     build-base     geos-dev     libxml2-dev     libxslt-dev     postgresql-dev     proj-dev     python3-dev   && pip3 install --upgrade pip setuptools   && pip3 install wheel   && pip3 install     gunicorn     lxml     parmap     psycopg2     sqlalchemy     xmltodict   && pip3 install pycsw==${PYCSW_VERSION}   && apk del .build-deps' returned a non-zero code: 1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by epifanio** [comment]
There has been a discussion on github pycsw channel about the pycsw docker image and which linux distribution to use as default. The decision was to switch the default docker image to be a debian based machine (debian is more development friendly and the image footprint is not a big concern).

The pycsw docker image on docker hub is kept up to date with the pycsw releases. It also has a (recently added) kubernetes settings.

As long as you are not planning to use custom pycsw src code (as I do for my testing to keep up with pycsw developmemt/debug) I suggest we use geopython/pycsw:2.6.0 image in production (or make a clone of it and store it on the met docker image provider).

**Comment by mortenwh** [comment]
@aheimsbakk @epifanio - is this still relevant?
